#!/usr/bin/bash
echo "Welcome to DeepFlow!"
dk="saditya88/deepflow:gpu"
if [ -z "$1" ]
then
    dk="saditya88/deepflow:gpu"
elif [ $1 == "cpu" ]
then
    dk="saditya88/deepflow:cpu"
else
    echo Unknwn input: "$1"
    echo Only 'cpu' is accepted as an input
    echo If you wish to use the GPU version, no arguments are required.
    exit
fi
output=$(pwd)/output/
mkdir -p "$output"
echo Using the Docker image: "$dk"
docker run -u=$(id -u $USER):$(id -g $USER) \
           -e DISPLAY=$DISPLAY \
           --gpus all \
           -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
           -v $(pwd)/assets:/assets \
           -v "$output":/output \
           -v ~/:/data/ \
           --rm \
           "$dk"